# Generated by Django 3.2.5 on 2021-10-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210923_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
